### ISSUE TITLE
[개발] 내역 컴포넌트

### ISSUE THREAD

**Issue by haeunkim428** [TimeSalad/client#6]
- 관련이슈 https://github.com/TimeSalad/client/issues/1

**Comment by haeunkim428** [comment]
- [ ] 메인 스크린
- [ ] 헤더
- [ ] 고정 메뉴 #20 
- [ ] 결과 탭
- [ ] 내역 탭
- [x] 단일 내역 컴포넌트 https://github.com/TimeSalad/client/issues/9
- [ ] 내역 추가 모달
- [x] 내역 추가 모달 내 단일 내용 컴포넌트 https://github.com/TimeSalad/client/issues/10
- [ ] 내역 추가 모달 내 카테고리 https://github.com/TimeSalad/client/issues/19
- [ ] 카테고리 설정 모달
- [ ] 카테고리 추가/편집 모달
- [ ] 세부 카테고리 추가 모달
- [ ] 세부 카테고리 아이콘 편집/추가 모달
